### ISSUE TITLE
RemovedInDjango110Warning issue

### ISSUE THREAD

**Issue by Jicehef** [django-import-export/django-import-export#380] opened 2016-01-05 15:59 UTC
virtualenvs/django19/lib/python3.4/site-packages/import_export/resources.py:492: RemovedInDjango110Warning: 'get_field_by_name is an unofficial API that has been deprecated. You may be able to replace it with 'get_field()'

**Comment by fabian** [comment] 2016-01-05 23:10
Duplicate of #369

**Comment by bmihelac** [comment] 2016-01-11 08:00
Fixed with 48b866e

**Closed by bmihelac** 2016-01-11 08:00 UTC
