### ISSUE TITLE
Demo not working out-of-the-box

### ISSUE THREAD

**Issue by fabaff** [django-import-export/django-import-export#1125] opened 2020-05-06 06:55 UTC
It looks like that there is an issue with the migrations for the demo. With the latest checkout I get:

```bash
$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
[....]
export/tests/core/migrations/0004_bookwithchapters.py", line 17, in <module>
    class Migration(migrations.Migration):
  File "/home/demo/Documents/repos/django-import-export/tests/core/migrations/0004_bookwithchapters.py", line 32, in Migration
    ('data', data_field)
NameError: name 'data_field' is not defined
```

**Comment by josx** [comment] 2021-11-09 18:54
Still now working.

I have Fixed by:
```diff
--- a/tests/core/migrations/0004_bookwithchapters.py
+++ b/tests/core/migrations/0004_bookwithchapters.py
@@ -2,6 +2,7 @@ from django.db import migrations, models

can_use_postgres_fields = False
chapters_field = models.Field()  # Dummy field
+data_field = models.Field()
```

**Comment by matthewhegarty** [comment] 2021-11-09 19:00
thanks for the update - please can you advise as to what version of django and django-import-export you are using?

**Comment by josx** [comment] 2021-11-09 19:14
Repo main HEAD: https://github.com/django-import-export/django-import-export/commit/8ac147d5d2775cd23026b153fd978a1492088251

**Comment by matthewhegarty** [comment] 2021-11-09 19:25
what version of django please

**Comment by josx** [comment] 2021-11-09 19:27
Django version:
```
Collecting Django>=2.2
Using cached Django-3.2.9-py3-none-any.whl (7.9 MB)
```

Some clues:

It seems that if i only install requirements from `base.txt` and run makemigrations` has this error:  `NameError: name 'data_field' is not defined`

After When I installed `test.txt` requirements and run `makemigrations`, has no error because tell me `No changes detected`

**Comment by josx** [comment] 2021-11-09 19:28
Anyways data_field is not defined  (not imported) in
https://github.com/django-import-export/django-import-export/blob/main/tests/core/migrations/0004_bookwithchapters.py#L32

**Comment by matthewhegarty** [comment] 2021-11-09 19:35
do you need to run makemigrations - why not just run migrate?

**Comment by matthewhegarty** [comment] 2021-11-09 19:36
ok, I can reproduce as follows:

1. checkout clean repo (v.2.6.1)
2. `mkvirtualenv -p `which python3.9` django-import-export-tst -r requirements/base.txt`
3. cd tests && ./manage.py migrate

**Comment by matthewhegarty** [comment] 2021-11-09 20:34
Thank you for your input @josx - I've created a PR from your patch to resolve this.

**Closed** 2021-11-10 08:54 UTC

**Comment by josx** [comment] 2021-11-11 15:37
@matthewhegarty testing and retesting all this I realize that there are a missing migration file, please check
https://github.com/django-import-export/django-import-export/pull/1346
