### ISSUE TITLE
DATETIME FORMAT FAILS W/O TRAILING COMMA FOR EOL

### ISSUE THREAD

**Issue by drewipson** [django-import-export/django-import-export#1262] opened 2021-04-01 00:42 UTC
**Describe the bug**
On my import data file, my last column is a date field. On import django-import-export throws an error saying the DATE format is invalid. Once I add a trailing comma to the end of the line, the error goes away and the import is successful.
**To Reproduce**
1. Create model with date field.
2. Create test file with date field as the last header in the CSV
3. Put in the correct date time format with no trailing comma.
4. Upload the file.

**Versions (please complete the following information):**
 - Django Import Export: 2.5.0
 - Python 3.9
 - Django  3.1.6

**Expected behavior**
The date format should be validated and the record created without a trailing comma.
**Screenshots**
### without the trailing comma
![Screen Shot 2021-03-31 at 6 40 30 PM](https://user-images.githubusercontent.com/24757991/113227725-97fe5a80-9250-11eb-9d1f-85e58e567f8b.png)
![Screen Shot 2021-03-31 at 6 39 37 PM](https://user-images.githubusercontent.com/24757991/113227671-743b1480-9250-11eb-82bc-0ba7018e387f.png)

### With the trailing comma
![Screen Shot 2021-03-31 at 6 39 01 PM](https://user-images.githubusercontent.com/24757991/113227636-5ec5ea80-9250-11eb-8aa9-d8b1a4d43712.png)
![Screen Shot 2021-03-31 at 6 42 18 PM](https://user-images.githubusercontent.com/24757991/113227838-d4ca5180-9250-11eb-8cef-26bc0e075d2e.png)

**Additional context**

**Comment by matthewhegarty** [comment] 2021-04-09 20:23
Hi Drew

thanks for raising this

> On import django-import-export throws an error saying the DATE format is invalid. 

In your example, the date is invalid according to the default format.  Does it work if you change the date to '2021-01-04'?  You can also add the correct format to your settings file:

```
DATE_INPUT_FORMATS=("%d-%m-%Y",)
```

> Once I add a trailing comma to the end of the line, the error goes away and the import is successful.

I'm confused about this and I couldn't reproduce it with the test app.  Does the import definitely work?  i.e. a row is created in the db with the correct date set?

**Comment by drewipson** [comment] 2021-04-13 14:48
@matthewhegarty 
Thanks for checking about the date format. I realize it's not the default but I've made the appropriate changes for the import date format to work successfully. As described in the issue, the only difference between a failed import and a successful one is the trailing comma.

**Comment by matthewhegarty** [comment] 2021-04-13 15:46
Are you able to reproduce this using the [example app](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app)?

**Comment by matthewhegarty** [comment] 2021-05-05 14:48
Closing for now. Please post back if you can reproduce this in the example app.

**Closed by matthewhegarty** 2021-05-05 14:48 UTC
Labels: bug
