### ISSUE TITLE
After import function is called 2 times 

### ISSUE THREAD

**Issue by AtulCIS** [django-import-export/django-import-export#1048] opened 2019-12-12 12:28 UTC
Hi I am importing a file and I want to delete all the data which is not in CSV file but present on DB so each time the CSV data is in the DB. Old data will be removed.

def after_import_instance(self, instance, new, **kwargs):
        """ For each row in the import file, add the pk to the list """
        if instance.pk:
            self.imported_rows_pks.append(instance.pk)

    def after_import(self, dataset, result, using_transactions, dry_run=False, **kwargs):
        """  delete all rows not in the import data set. Then call the same method in the parent to still sequence the DB """
        ids = list(set(self.imported_rows_pks))
        Product.objects.exclude(pk__in=ids).delete()
        import_export.resources.ModelResource.after_import(self, dataset, result, using_transactions, dry_run, **kwargs)

My code is running 2 times can you help me on it. I think the function called one time when confirm import is triggered.

**Comment by raphodn** [comment] 2020-05-28 15:11
Hi, just to share that I faced the same problem. The difference in these 2 times is the `dry_run` field.
- the first time (after you select the file and click on import), `dry_run` is `True`
- the second time (after you click on confirm), `dry_run` is `False`

**Comment by andrewgy8** [comment] 2020-05-28 15:55
Is this a duplicate of #1137?

**Comment by raphodn** [comment] 2020-05-28 17:29
Probably !

I haven't dug much into the transaction/rollback side of things.

In my case I would usually try to import a file, and only confirm if there were no errors or invalid rows. If that happens, I would fix the errors (in my case usually unknown M2M fields) and re-import the file. And the modified rows would show up as update again, not as skip, so i don't have that "double insert behavior" (also all my rows, even the new ones, have a unique id)

**Comment by Giribushan** [comment] 2020-12-31 04:24
> Hi, just to share that I faced the same problem. The difference in these 2 times is the `dry_run` field.
> 
> * the first time (after you select the file and click on import), `dry_run` is `True`
> * the second time (after you click on confirm), `dry_run` is `False`

Saved my day!!

**Closed** 2020-12-31 14:06 UTC
