### ISSUE TITLE
id field increases twice in django-import-export? 

### ISSUE THREAD

**Issue by maqsoodhakro** [django-import-export/django-import-export#1308] opened 2021-08-09 06:07 UTC
Hello everyone!
I am facing problem while uploading data file in json/csv via django-admin interface with import export option. when i upload data file , id field increases twice as records in file? how to solve this issue?

**Comment by matthewhegarty** [comment] 2021-08-09 10:21
This could be a duplicate of #1078.  Also mentioned in #1182 and #1183.  I suggest to read through those threads and let us know if this explains what you are seeing.

**Comment by maqsoodhakro** [comment] 2021-08-09 10:47
i have been reading this for last few days, but i can figure out what's proper solution? can you please guide me. I am using postgresql database.

**Comment by smednikar** [comment] 2021-09-03 14:10
I followed the solution posted at

https://simathapa111.medium.com/how-to-upload-a-csv-file-in-django-3a0d6295f624

**Comment by pokken-magic** [comment] 2022-04-22 02:42
#1227 explains that this is db specific behavior so I think we should close these old issues. It’s not something import export has control over (the transaction behavior of django and a db).

**Closed by pokken-magic** 2022-04-22 02:42 UTC
Labels: duplicate, question
