### ISSUE TITLE
raise Error when model  has attribute __unicode__ which print some foreignKey value.

### ISSUE THREAD

**Issue by GuihaiHU** [django-import-export/django-import-export#493] opened 2016-07-15 10:41 UTC
If A model has attribute `__unicode__`, foreignKey and print the foreignKey in `__unicode__`, when I import some new data, it will raise an Exception says `RelatedObjectDoesNotExist: XX has no yy.`
For example

```python
## models.py
title = models.CharField(verbose_name=u'需求内容')
proposer = models.ForeignKey(User, verbose_name=u'需求提出人', related_name='proposer')
    def __unicode__(self):
        return u'%s %s' % (self.proposer.username, self.title )
```

After reading the code in django-import-export, I found something wrong as follow:

```python
## resource.py
instance, new = self.get_or_init_instance(instance_loader, row)  # if row is new, will return an None instance
row_result.object_repr = force_text(instance) # try to get the foreignKey value, and raise Exception
```

**Comment by thauk-copperleaf** [comment] 2016-07-19 23:07
> `instance, new = self.get_or_init_instance(instance_loader, row)  # if row is new, will return an None instance`

The instance loader should always return an object for `instance`. If the row is new, then the only difference is `new` will be `True`. That's what the name of the function means: if the instance exists, get it, otherwise init a new instance.

**Comment by GuihaiHU** [comment] 2016-07-20 00:48
Does it mean I need to override the `init_instance` , otherwise it will raise Exception when using `__unicode__`  for  new row

**Comment by thauk-copperleaf** [comment] 2016-07-20 16:01
I'm not sure if you need to override `init_instance` or if it's necessary.

What exactly is raising an Exception? Do you have a callstack?

**Comment by JarnoRFB** [comment] 2016-07-20 17:45
You can except the error in your model's  `__unicode__` method as in #439. However it's probably better to only except the specific error instead of using the broad except with

```python
from django.core.exceptions import DoesNotExist
```
Yet I think this is an issue with `django-import-export` and should be fixed at some point.

**Comment by GuihaiHU** [comment] 2016-07-21 00:45
Thank  @JarnoRFB  and  @thauk-copperleaf  for replying.

**Comment by thauk-copperleaf** [comment] 2016-07-21 16:03
@JarnoRFB I'm not sure how this could be fixed. In #439 was your proposal to not call `Resource.save_instance()` (which calls `Model.save()`) in `Resource.import_row()`?

**Comment by JarnoRFB** [comment] 2016-07-21 16:36
I think my proposal in #439 is pretty much bullshit. I thought if the models are first instantiated in the dry_run and saved only in the real import they would have the `related_model`, but isn't that what is already happening?
 Now I think just wrapping
```python
row_result.object_repr = force_text(instance)
```
in a `try  - exept`  block would maybe do it. Or maybe the issue is with 
```python
instance, new = self.get_or_init_instance(instance_loader, row)
``` 
returning something strange for new rows as @GuihaiHU pointed out.

**Comment by thauk-copperleaf** [comment] 2016-07-21 17:14
I think you're on to something there. I see that line twice inside `Resource.import_row()`, actually. That's a little wonky. I guess it's recording what the object is immediately since it might get deleted or skipped, and then again since saving it could change its representation (like in this case, with a field that is a foreign key). I suppose wrapping the first call in a try/except would be sufficient...

**Closed** 2016-09-07 06:40 UTC
