### ISSUE TITLE
String fields with number are considered numeric and it causes a Numeric Overflow error

### ISSUE THREAD

**Issue by lugezz** [django-import-export/django-import-export#1497] opened 2022-10-15 14:27 UTC
**String fields with number are considered numeric and it causes a Numeric Overflow error**
When importing an Excel Spreadsheet string fields with number are considered numeric and it causes a Numeric Overflow error.

For instance in the file attached you will find 2 columns (CUIT and CUIL), those are CharField on the app models

**To Reproduce**

1. Import file
2. Result get True on result.has_errors()

**Versions (please complete the following information):**
 - Django Import Export: 2.9.0
 - Python: 3.10.6
 - Django: 4.1.1

**Expected behavior**
Import with no errors

**Screenshots**
[Import empleados.xlsx](https://github.com/django-import-export/django-import-export/files/9792278/Import.empleados.xlsx)
![image](https://user-images.githubusercontent.com/41469771/195991485-ddb13298-5dce-4b13-a7f8-0f58a2bd0a97.png)

**Additional context**

** resourses.py **
```
class EmpleadoResource(resources.ModelResource):
    empresa = fields.Field(
        column_name='CUIT', attribute='CUIT Empresa',
        widget={
            ForeignKeyWidget(Empresa, 'cuit'),
            CharWidget()
            })
    leg = fields.Field(column_name='Leg')
    name = fields.Field(column_name='Nombre')
    cuil = fields.Field(column_name='cuil',
                        widget=CharWidget())

    class Meta:
        model = Empleado
        fields = ('empresa', 'leg', 'name', 'cuil')
```

** models.py **

```
class Empresa(models.Model):
    name = models.CharField(max_length=120, verbose_name='Razon Social')
    cuit = models.CharField(max_length=11, validators=[MinLengthValidator(11)])

class Empleado(models.Model):
    leg = models.PositiveSmallIntegerField()
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    name = models.CharField(max_length=120, verbose_name='Nombre', null=True, blank=True)
    cuil = models.CharField(max_length=11, validators=[MinLengthValidator(11)])
```

** views.py **

```
def import_empleados(request):
    context = {
        'error': '',
        'results': ''
    }

    if request.method == 'POST':
        empleado_resource = EmpleadoResource()
        dataset = Dataset()
        nuevos_empleados = request.FILES['xlsfile']
        print(nuevos_empleados)
        try:
            imported_data = dataset.load(nuevos_empleados.read())
            print(imported_data)
            result = empleado_resource.import_data(dataset, dry_run=True)
        except UnsupportedFormat:
            context['error'] = "Formato de archivo incorrecto"
        except Exception as err:
            context['error'] = f"Unexpected {err=}, {type(err)=}"

        if not result.has_errors():
            print(result)

    return render(request, 'export_lsd/export/empleados.html', context)
```

**Comment by matthewhegarty** [comment] 2022-10-26 15:51
Thanks for raising - we'll look into it

**Comment by matthewhegarty** [comment] 2022-10-26 19:04
Hi - I can't reproduce this using the [Example Application](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app).  I notice that you are using a custom import function which could be related to the problem.

 Is it possible you can try using [v3.0](https://pypi.org/project/django-import-export/)?  If it is still an issue, can you reproduce using the Example application?  Can you provide a full stack trace of the error?

**Comment by lugezz** [comment] 2022-10-28 21:05
Good afternoon Matthew, I installed version 3.0.1 and it's working fine. Thanks a lot for your help, I'm sorry I haven't considered this new version.

**Comment by matthewhegarty** [comment] 2022-10-28 21:06
That's good to hear.  Thanks for confirming.  Are you ok for me to close the issue?

**Comment by lugezz** [comment] 2022-10-28 21:08
Yes, please. Thank you very much for all!

**Closed** 2022-10-29 16:55 UTC
Labels: bug
