### ISSUE TITLE
datetime field localtime() issue

### ISSUE THREAD

**Issue by MrAlexWinkler** [django-import-export/django-import-export#1165] opened 2020-07-22 06:53 UTC
**Describe the bug**
Django DateTime Import

**To Reproduce**
Import DateTime data and you'll hit a "localtime() cannot be applied to a naive datetime", I've been using the package for a while now and use the admin import page as well as a custom import page for users. Both work fine for non-datetime data.

I've tried this with adding with tz +00 and without
2020-07-17 7:42:39
2020-07-17 7:42:39+00

I've tried the DateTimeWidget where
format="%Y-%m-%d %H:%M:%S"
format="%Y-%m-%d %H:%M:%S$z"
format=None

I've posted a SOF question regarding it
https://stackoverflow.com/questions/62990575/django-import-export-datetime-naive-datetime-error

And had a convo specific to it on SOF
https://chat.stackoverflow.com/rooms/218260/django-import-export

The end result seems that the issue may be in the django-import-export package.

**Versions (please complete the following information):**
 - django-import-export==2.2.0
 - Python 3.7.4
 - Django==3.0.2

settings.py
```
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True
```

**Expected behavior**
I was expecting the datetime to import the dates in my csv file

**Screenshots**
View 2 links above

**Additional context**
View 2 links above

**Comment by matthewhegarty** [comment] 2020-07-22 07:00
Alex and I discussed this on SO chat.  The issue seemed to be that when a naive datetime was imported via the Admin console, then it couldn't be displayed because the `render()` method in `DateTimeWidget` couldn't handle a naive datetime.
However I couldn't reproduce this issue.  I'll do some more research, but my current thinking is that it is not a bug.

**Comment by MrAlexWinkler** [comment] 2020-07-22 07:40
If i leave Time_Zone = 'UTC' but comment out Use_TZ = True
With this data
date,id,amount,price,fee,entry_type,reg_fee
2020-07-17 7:42:39,,40,14.56,0,Entry,0
2020-07-17 7:42:39,,40,14.56,0,Entry,0
Then it imports. Still not sure where the issue lies with USE_TZ=True is not commented out

**Comment by matthewhegarty** [comment] 2020-07-22 07:46
In that case you have disabled Timezone support, so there is no [conversion of a naive datetime to tz aware](https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L214).  This is saying that you are ok with naive datetimes in your database, which could cause you problems down the line, depending on the nature of your app.  You'll need to think carefully if you want to disable timezones (more info [here](https://docs.djangoproject.com/en/3.0/topics/i18n/timezones/)).

**Comment by matthewhegarty** [comment] 2020-07-22 07:51
This code reproduces your issue, but this shouldn't happen in normal operations, because `render()` should never be passed a naive datetime:

```python
    w = widgets.DateTimeWidget(format="%Y-%m-%d %H:%M:%S")
    print(w.render(parse_datetime('2020-07-20 0:00:00')))
```

**Comment by MrAlexWinkler** [comment] 2020-07-22 08:52
> In that case you have disabled Timezone support, so there is no [conversion of a naive datetime to tz aware](https://github.com/django-import-export/django-import-export/blob/master/import_export/widgets.py#L214). This is saying that you are ok with naive datetimes in your database, which could cause you problems down the line, depending on the nature of your app. You'll need to think carefully if you want to disable timezones (more info [here](https://docs.djangoproject.com/en/3.0/topics/i18n/timezones/)).

The imported datetimes are showing up as 2020-07-21 07:25:56+00 in the database although in the csv file are 2020-07-21 07:25:56

Does that not mean they are NOT naive? As the have tz attached since my TIME_ZONE = 'UTC' ?

---

Thanks for helping me with this and awesome that you were able to recreate the issue. I'm really wondering where the discrepancies happen.

**Comment by matthewhegarty** [comment] 2020-07-22 09:18
If `USE_TZ` is not set, then it is disabled by default.  So having `TIME_ZONE` set won't make any difference (at least for `django-import-export`).  It depends on your database, but storage could be in UTC by default ([Postgres](https://docs.djangoproject.com/en/3.0/topics/i18n/timezones/#postgresql) does this).

**Comment by matthewhegarty** [comment] 2020-07-23 09:15
Hi @MrAlexWinkler I couldn't reproduce this issue using the Admin console.  Is there anything you would like to add or can I close the issue?

**Comment by MrAlexWinkler** [comment] 2020-07-23 17:24
I guess we could close it for now. However, the original issue is still not solved. 
If I have new info should I add it here after the ticket is closed?

**Comment by matthewhegarty** [comment] 2020-07-23 18:04
Yes, my view is that it is an issue with your project, rather than with `django-import-export`, because I was unable to reproduce it with the information you supplied.  If you can reproduce it, then please provide details here and I'll look into it.

**Comment by rsasidharan01** [comment] 2021-09-22 15:15
I was able to reproduce it, and needed to comment out USE_TZ

**Comment by rsasidharan01** [comment] 2021-09-22 15:15
is it a package problem or a database issue?

**Comment by matthewhegarty** [comment] 2021-09-22 20:24
Can you reproduce this using the test application?

**Comment by geminsky** [comment] 2021-09-26 16:35
I think this happens when the server time zone and local time zone are different

**Comment by ohbob** [comment] 2021-10-06 16:19
had the same problem today. exported data, deleted data, imported and got that error.

**Comment by rsasidharan01** [comment] 2021-11-24 17:30
> had the same problem today. exported data, deleted data, imported and got that error.

did you find a fix?

**Comment by MohGinanjar** [comment] 2022-06-01 01:43
I've tried commenting #USE_TZ = True

and work

**Comment by vanschelven** [comment] 2022-07-27 08:16
> this shouldn't happen in normal operations, because render() should never be passed a naive datetime

I have encountered at least one path in which `render` is indeed passed a naive datetime, as the output of `clean` while showing a diff as mentioned in the original bug-report. Namely, when the original file contains actual datetimes rather than strings:

https://github.com/django-import-export/django-import-export/blob/2c1dac5747c732cb1100bf59fea4b5f13370b00b/import_export/widgets.py#L217

**Comment by matthewhegarty** [comment] 2022-07-27 09:00
> I have encountered at least one path in which render is indeed passed a naive datetime, as the output of clean while showing a diff as mentioned in the original bug-report.

Can you create a test case which reproduces this issue?

**Comment by vanschelven** [comment] 2022-07-27 10:08
A reliable series of steps is:

* change `tests/settings.py` to contain `USE_TZ = True`
* edit `books.xlsx` to have a column "added" with an actual datetime in it. LibreOffice will do this automatically if you just type anything that's a valid datetime, and I assume Microsoft Office will do the same.
* do the import

**Comment by matthewhegarty** [comment] 2022-09-02 12:40
Re-open - I think this affects `DateWidget` as well

**Comment by matthewhegarty** [comment] 2022-09-02 14:18
Closing again - *does not* affect `DateWidget` because it has [no TZ information](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects).

> For applications requiring aware objects, [datetime](https://docs.python.org/3/library/datetime.html#datetime.datetime) and [time](https://docs.python.org/3/library/datetime.html#datetime.time) objects have an optional time zone information attribute, tzinfo, that can be set to an instance of a subclass of the abstract [tzinfo](https://docs.python.org/3/library/datetime.html#datetime.tzinfo) class. These [tzinfo](https://docs.python.org/3/library/datetime.html#datetime.tzinfo) objects capture information about the offset from UTC time, the time zone name, and whether daylight saving time is in effect.

**Closed by matthewhegarty** 2022-09-02 14:18 UTC
Labels: bug
