### ISSUE TITLE
Need row parameter for Resource.skip_row method

### ISSUE THREAD

**Issue by okapies** [django-import-export/django-import-export#1098] opened 2020-03-17 03:05 UTC
`skip_unchanged` still doesn't work for Many-to-Many (M2M) fields as described in #385. As commented by @irsalmashhor (https://github.com/django-import-export/django-import-export/issues/385#issuecomment-385288150), I think we need to pass `row` value to `skip_row` to inspect M2M field in the instance. Any ideas?

**Comment by matthewhegarty** [comment] 2021-05-05 20:36
This is addressed in #1271. I'll close this as the issue is addressed in #1270.

**Closed by matthewhegarty** 2021-05-05 20:36 UTC
