### ISSUE TITLE
Customize admin import forms problem 

### ISSUE THREAD

**Issue by alih552** [django-import-export/django-import-export#1123] opened 2020-05-05 05:52 UTC
Following the docs (getting started) in the last section I got a problem.
Everything works fine and the Author form shows normally but when I select the author and send an .xlsx file it doesn't update the author field even after I confirm the import, it doesn't update the author field.
and this's the code that I'm talking about from the docs : 
```
from import_export.admin import ImportMixin
from import_export.forms import ImportForm
from import_export.forms import ConfirmImportForm
from django import forms

class CustomImportForm(ImportForm):
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        required=True)

class CustomConfirmImportForm(ConfirmImportForm):
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        required=True)

class BookResource(resources.ModelResource):

    class Meta:
        model = Book

class CustomBookAdmin(ImportMixin, admin.ModelAdmin):
    resource_class = BookResource

    def get_import_form(self):
        return CustomImportForm

    def get_confirm_import_form(self):
        return CustomConfirmImportForm

    def get_form_kwargs(self, form, *args, **kwargs):
        # pass on `author` to the kwargs for the custom confirm form
        if isinstance(form, CustomImportForm):
            if form.is_valid():
                author = form.cleaned_data['author']
                kwargs.update({'author': author.id})
        return kwargs


admin.site.register(Book, CustomBookAdmin)```

**Comment by matthewhegarty** [comment] 2020-05-05 13:21
Can you be more specific about what the issue is?  I tried an Author import (xlsx) using the example app and it imported fine.  I also checked that an Author update from the file worked ok.

Can you prove that it's not working using the example app? If so, can you supply the steps to reproduce?

**Comment by c3dr** [comment] 2020-09-04 17:01
> Hi, I have similar issue.
> My problem that a get form class but not form class instance onto the `form` argument of `get_form_kwargs` method.

Exactly the same for me, did you find something?

**Comment by michaelachrisco** [comment] 2020-09-21 17:03
Using Django 3.0.4 I am having the same issue. 

When I did a bit of debugging, I found that `if isinstance(form, CustomImportForm):` was always returning `False` in the above example, so the `author` would never get passed in and updated.

**Comment by andrewgy8** [comment] 2020-09-24 11:04
Interesting. I was working on another lib a few weeks ago, and ran into an issue with `isinstance` usage. [I had to also use `issubclass`](https://github.com/mercadona/rele/blob/master/rele/config.py#L78). Could it be related?

**Comment by michaelachrisco** [comment] 2020-09-24 23:42
> Interesting. I was working on another lib a few weeks ago, and ran into an issue with `isinstance` usage. [I had to also use `issubclass`](https://github.com/mercadona/rele/blob/master/rele/config.py#L78). Could it be related?

@andrewgy8 I just did the same as your solution here:
```
    def get_form_instance(self, attribute):
        try:
            if isinstance(attribute, CustomImportForm):
                subscription = attribute
            elif issubclass(attribute, CustomImportForm):
                subscription = attribute()
            else:
                return None
        except TypeError:
            # If attribute is not a class, TypeError is raised when testing issubclass
            return None
        return subscription

    def get_form_kwargs(self, form, *args, **kwargs):
        # pass on `user_type` to the kwargs for the custom confirm form
        print(isinstance(form, CustomImportForm))
        subscription = self.get_form_v1(form)
        if subscription and subscription.is_valid():
            user_type = subscription.cleaned_data['user_type']
            kwargs.update({'user_type': user_type.id})
        return kwargs
```

And I can confirm it seems to go farther this time. This time, it does not skip the kwargs and passes in (in this case) the user_type id. The behaviour seems to be the same, but with a different path. The kwargs now have the id within it, but its not updating the confirmation screen with the value. Ill try modifying the resources.

**Comment by michaelachrisco** [comment] 2021-09-24 19:33
I got this working a while back....by monkey patching a large method within the library. We have sense moved on from using this library, but I would suggest waiting until: django-import-export/django-import-export#1185
is pulled in or something similar since its a bit old.

**Comment by matthewhegarty** [comment] 2023-04-12 18:26
django-import-export v3 refactored the hooks for extending admin forms.  The documentation is [here](https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#admin-integration).  Since there have been no recent updates on this issue I will close it.  If anyone can reproduce (or confirm it's working) please add a comment.

**Closed by matthewhegarty** 2023-04-12 18:26 UTC
Labels: hacktoberfest
