### ISSUE TITLE
Id getting created twice once during preview and after import

### ISSUE THREAD

**Issue by smednikar** [django-import-export/django-import-export#1183] opened 2020-09-08 16:44 UTC
In my django project, i am doing an import via admin. currently my database is empty with Id as 0. I got 7 rows in my csv file and during the preview the ids get generated from 1 to 7. After i confirm import, in my database the Ids are from 8 to 14. 

I tried with True and False for IMPORT_EXPORT_USE_TRANSACTIONS but same result. And in model managed is set to False
Why it is not using the id created in the preview or how to avoid this?

mysql  Ver 8.0.17 for Win64 on x86_64 (MySQL Community Server - GPL)
latest version of django-import-export
latest version of django

![database after import](https://user-images.githubusercontent.com/70968055/92504695-9facd200-f220-11ea-89f0-d479816f5189.png)
![preview](https://user-images.githubusercontent.com/70968055/92504700-a1769580-f220-11ea-973b-78f042b28650.png)

**Comment by andrewgy8** [comment] 2020-09-09 09:28
Can this be a duplicate of #1182 ?

**Comment by smednikar** [comment] 2020-09-09 14:04
Yes.. almost..  I am using the Admin page for Importing and not sending any email or additional processing. If this is known issues/bug, then needs to be fixed at the earliest as this causing further issues with applications when using the id as primary key,

**Comment by smednikar** [comment] 2020-09-09 14:04
Yes.. almost..  I am using the Admin page for Importing and not sending any email or additional processing. If this is known issues/bug, then needs to be fixed at the earliest as this causing further issues with applications when using the id as primary key,

**Comment by smednikar** [comment] 2020-09-09 14:05
Yes.. almost..  I am using the Admin page for Importing and not sending any email or additional processing. If this is known issues/bug, then needs to be fixed at the earliest as this causing further issues with applications when using the id as primary key,

**Comment by andrewgy8** [comment] 2020-09-09 14:28
> needs to be fixed at the earliest

I should assign the issue to you?

**Comment by smednikar** [comment] 2020-09-09 14:32
For python/django I am at  beginner level.. otherwise I would have done it...

**Comment by maqsoodhakro** [comment] 2021-08-09 10:50
@smednikar I have same issue bro, did you solve it? i have searching for last few days but have not found any proper solution.

**Comment by smednikar** [comment] 2021-09-03 14:08
> @smednikar I have same issue bro, did you solve it? i have searching for last few days but have not found any proper solution.

I followed the solution posted at

https://simathapa111.medium.com/how-to-upload-a-csv-file-in-django-3a0d6295f624

**Comment by maqsoodhakro** [comment] 2021-09-06 08:50
I searched a lot on the internet about this, but I have not found any
proper solution so I tried another option for uploading and exporting data
about my project. For importing data, I create temp tables with JSONFIELD
and transfer data from temp tables to actual ones with logic. For exporting
data, I created my own method at admin.py for exporting files (JSON).
Furthermore, I must tell you that this import-export library not only
contains problems related to the primary key column but I found the same
problem with every numeric column. thanks

**Comment by matthewhegarty** [comment] 2021-09-06 10:30
> I must tell you that this import-export library not only
contains problems related to the primary key column but I found the same
problem with every numeric column

Hi @maqsoodhakro can you give us more details or provide a link to an existing issue so we can look into it?

**Comment by matthewhegarty** [comment] 2023-04-12 18:19
This is a [known issue](https://django-import-export.readthedocs.io/en/latest/faq.html#ids-incremented-twice-during-import).
Closing.

**Closed by matthewhegarty** 2023-04-12 18:19 UTC
Labels: duplicate
