### ISSUE TITLE
Microsoft Excel is not reading exported file correctly

### ISSUE THREAD

**Issue by HoshiYamazaki** [django-import-export/django-import-export#1070] opened 2020-01-23 10:54 UTC
Library version on my project: 1.2.0

If I try to read exported CSV file on macOS or Windows, it is not reading correctly on Microsoft Excel.
It get replaced with random characters like beginning of this:
![image](https://user-images.githubusercontent.com/21007545/72978057-04bcd000-3dd6-11ea-9003-5148b54741d5.png)

Seems like this is this bug:
http://www.openforis.org/support/questions/279/wrong-characters-display-when-exporting-files-to-csv-from-collect

I tried to set `to_encoding` in admin to `utf-8`, `cp1252`, and also `utf-8-sig`.
How I can fix that to support Microsoft products?

Seems that I need to set `iso` encoding, which is the best way to do this?

**Comment by andrewgy8** [comment] 2020-05-28 07:23
Please dont create two different issues for the same question. Duplicate of #1090 and #1141

**Closed by andrewgy8** 2020-05-28 07:23 UTC
