### ISSUE TITLE
[3.x] ManyToMany values are not always compared correctly

### ISSUE THREAD

**Issue by manelclos** [django-import-export/django-import-export#1390] opened 2022-02-08 10:45 UTC
The new code comparing ManyToManyWidget using the future value to check if values are equal, needs to sort the resulting list before comparing, otherwise same values in different other will trigger an update operation when nothing has really changed.

**To Reproduce**
1. Import a ManyToMany relationship in which the order from the database does not match with the order on the imported file

e.g.: original value: `[<Model pk 1>, <Model pk 2>]`, instance value to import: `[<Model pk 2>, <Model pk 1>]`

**Versions (please complete the following information):**
 - Django Import Export: 3.x

**Expected behavior**
Should not trigger an update

**Comment by matthewhegarty** [comment] 2022-04-05 10:38
Hi Manel

I looked into this and couldn't reproduce - it looks like the changes you made in [latest commit](https://github.com/django-import-export/django-import-export/pull/1391/commits/a3d9ba97f1e87528982a3d89a16798d84bf32334) have solved it?

I created a test for this case anyway:

[test-resources-m2m-widget.txt](https://github.com/django-import-export/django-import-export/files/8417263/test-resources-m2m-widget.txt)

lmk if I can help get this closed :+1:

**Comment by matthewhegarty** [comment] 2022-04-06 09:16
I picked this up so we can get it into release 3.  Hope that's ok.

**Comment by manelclos** [comment] 2022-04-06 14:19
Sure it is. Keep it up :)

**Comment by matthewhegarty** [comment] 2022-04-07 12:11
Fixed in [release 3](https://pypi.org/project/django-import-export/3.0.0b0/)

**Closed** 2022-05-11 12:00 UTC
Labels: bug
